# ================================================
# DOCKER COMPOSE - AZURE
# ================================================

version: '3.8'

services:
  mesh-platform:
    image: meshbrainregistry.azurecr.io/mesh-platform:latest
    container_name: mesh-platform-prod
    restart: unless-stopped
    ports:
      - "3978:3978"
    environment:
      - NODE_ENV=production
      - PORT=3978
      - LOG_LEVEL=info
      - MicrosoftAppId=${MicrosoftAppId}
      - MicrosoftAppPassword=${MicrosoftAppPassword}
      - MicrosoftAppTenantId=${MicrosoftAppTenantId}
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPINSIGHTS_CONNECTION_STRING}
    env_file:
      - .env.azure
    secrets:
      - app-password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3978/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

secrets:
  app-password:
    external: true